### ISSUE TITLE
Compare performance and accuracy for using mean area and pixel area

### ISSUE THREAD

**Issue by thomas-maschler** [gfw-api/gfw-raster-analysis-lambda#18]
When used for larger tiles, the mean area approach might reduce the accuracy of the results quite a bit.
In this case it will be would be better to use the actual pixel area.

The below link shows an example on how you would do that
https://github.com/wri/raster2points/blob/master/raster2points/raster2points.py#L208-L241

The input array would be already fully masked. You would only need to calculate the lat coordinate and only return the area.

This will return a `float32` array. If memory becomes an issue you could try to cast it to a `float16` or `uint` and see if it significantly effects accuracy. The function calculates area in m2 and we will later convert it to ha. Do dropping some digits might not have too much of an effect.

**Comment by jterry64** [comment]
For reference, this is one the larger geometries the service can handle: Polygon (((-55.89450636942674322 -11.55071656050955298, -54.17571656050954942 -11.43702229299362827, -54.17571656050954942 -11.43702229299362827, -54.19578025477706262 -12.13925159235668616, -54.00851910828024671 -13.48351910828025346, -55.11871019108279768 -14.00851910828025382, -56.20214968152865254 -13.6975318471337566, -56.28909235668788824 -12.40676751592356553, -55.89450636942674322 -11.55071656050955298))

Latitude ranges between:
-11.43702229299362827 degrees, where pixel area = 754.4383057128906 Ha
-14.008519108280254 degrees, where pixel area = 747.0236632595487 Ha

Mean pixel area = 750.7516742892795 Ha

**Comment by jterry64** [comment]
Implemented getting the area using the actual pixel area per latitude. For the geometry above:
-Area using mean pixel method: 5857262.220529953 Ha
-Area using actual pixel area method: 5718766.846755759 Ha
-Area calculated in QGIS: 5718766.94931 Ha

So vs. QGIS, the mean method is off by ~2.4%, and pixel area is off by like 0.0000017%

**Comment by thomas-maschler** [comment]
Thanks for confirming this.
Than let's switch to the actual pixel area

**Comment by jterry64** [comment]
It does unfortunately have performance implications. For the way you implemented it in the raster2points repo, it adds ~3.75 seconds for analyzing the above polygon, mostly for calling get_area on every non-masked pixel. I got it down to ~0.7 s by only calling get_area on each lat value only once, and then to ~0.25 s by front loading some of the work in another thread while retrieving rasters from S3. That seems like an acceptable performance cost for the increased accuracy.

**Comment by thomas-maschler** [comment]
That makes sense. Sounds good.

**Comment by jterry64** [comment]
bf0430212e79080352030b2825b1f03773d6c82b
