### ISSUE TITLE
Avoid having to add pixel buffer

### ISSUE THREAD

**Issue by thomas-maschler** [gfw-api/gfw-raster-analysis-lambda#5]
`get_window_and_affine` function currently adds a pixel buffer to the read window at bottom and right side. Without this  buffer we cannot create the mask. 
https://github.com/gfw-api/gfw-raster-analysis-lambda/blob/master/raster_analysis/io.py#L134-L135

However, we need to read more COG blocks like this and it would be ideal if we could avoid this or remove the buffer again before reading the image

**Comment by jterry64** [comment]
You said the function was copied from another project, is this pixel buffer issue something that comes up in all projects it's used? I think the issue might just be a small bug in the geoprocessing code for this project

**Comment by thomas-maschler** [comment]
yes, this function was first published here
https://github.com/mmcfarland/foss4g-lambda-demo/blob/master/geop/geo_utils.py

**Comment by jterry64** [comment]
Removed and everything seems to work correctly
